### ISSUE TITLE
What do we set the "group" to?

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_deputies#2]
https://github.com/openaustralia/ukraine_verkhovna_rada_deputies/blob/master/scraper.rb#L68

Party and faction are separate concepts in the parliament and faction reportedly changes frequently. What should the "group" field be set to?

May we should ask for advice here? https://github.com/everypolitician/everypolitician-data/issues/111

**Comment by tmtmtmtm** [comment]
The role of parties vs factions is different in different countries, but generally in EveryPolitician, we primarily care about the faction, as that's what's actually important from day to day in most places, rather than which party they were elected as part of. Ideally we track all the changes as separate rows, per http://everypolitician.org/submitting.html

**Comment by henare** [comment]
Excellent, thanks @tmtmtmtm! I'll set it to the faction.
