### ISSUE TITLE
Small changes of MPs description

### ISSUE THREAD

**Issue by lisoffsky** [openaustralia/ukraine_verkhovna_rada_deputies#21]
If it is possible, on page of each MP elected in single mandate district, can we after number of district add oblast in brackets? e.g. “Виборчому округу №207 (Чернігівська область)”. That gives more understanding.

like this, for example https://tvfy-ukraine.oaf.org.au/people/rada/%D0%92%D0%B8%D0%B1%D0%BE%D1%80%D1%87%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83_%E2%84%96207/%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BB%D1%96%D0%B9_%D0%84%D0%B2%D0%BB%D0%B0%D1%85%D0%BE%D0%B2

And for MPs elected by party lists can we also add some adjustments?
To change on MP page text “for Загальнодержавному багатомандатному округу” on “обраний в Раду за списком партії” (means: was elected by party list)

**Comment by henare** [comment]
> If it is possible, on page of each MP elected in single mandate district, can we after number of district add oblast in brackets? e.g. “Виборчому округу №207 (Чернігівська область)”. That gives more understanding.

That sounds like a great idea @lisoffsky :+1: 

Do you think it would make more sense to have the oblast name _only_, e.g. "Чернігівська область"?

I think that is what is suggested on #6 and would be a good idea to do because it's more understandable for people.

> And for MPs elected by party lists can we also add some adjustments?
> To change on MP page text “for Загальнодержавному багатомандатному округу” on “обраний в Раду за списком партії” (means: was elected by party list)

I think the data should still say "Загальнодержавному багатомандатному округу" so we should keep it the same on this repository. However we can change that on the application so I've opened a new issue there to do this: https://github.com/OPORA/publicwhip/issues/141

**Comment by lisoffsky** [comment]
so changing this text from "for Виборчому округу №123" to "Львівська область". I like this plan.

**Comment by henare** [comment]
:+1: great, let's do this as part of #6 and close this then.
